### ISSUE TITLE
sshfs memory leak at idle

### ISSUE THREAD

**Issue by akissz** [osxfuse/sshfs#66]
I had some kind of memory leak recently with sshfs version 2.5.0, FUSE library version: 2.9.9, macOS 10.15.6. The sshfs was using over 6gb of ram during idle. I noticed my disk was filling up and computer was warm. Then I notice the high ram usage with sshfs. Killed the applications and restarted apps and now sshfs is using a little over 2mb ram. Sorry I don't have more info for this issue. Ask me questions if you have a question.

**Comment by aaronkogan** [comment]
The same problem - apple sillicon MacOS Ventura 13.1, sshfs use rosetta and leaks on 5 - 6 mb every 2 seconds. It happens when i just watch video 4k through Movist Pro. When i copying files in Finder or mc it leaks on 0.8mb per 2 secs.
I use to -o nolocalcaches,cache=no and it doesn't helps also.

SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9

**Comment by wuc9521** [comment]
I know little about memory leak but I guess it's the same problem here. Apple sillicon MacOS Ventura 13.2.1 and I met very serious crash as I ran `xxxx sshfs -C -o reconnect,password_stdin xxxxx xxxxxx`, when I could not open any of my applications and have to force quit each of them.

**Comment by bfleischer** [comment]
This repository is outdated. All macOS specific changes have been merged into the upstream repository at https://github.com/libfuse/sshfs. Future development will continue there.

Is the latest SSHFS 2.10 release on https://macfuse.io still leaking memory? If so, please open an issue in the upstream repository.
